apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hk2xsptux-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hk2xsptux-java-springboot-gitops